### ISSUE TITLE
ACME issue and possible initial state issue

### ISSUE THREAD

**Issue by server-nova** [james-lawrence/bw#41]
Hi James,
I faced with letsencrypt rate issue:
```
Sep 23 07:57:00 nsuite-dev-715g bw[4226]: [AGENT] 2024/09/23 07:57:00 diskcache.go:189: unable to retrieve certificate acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: *.sso.dev.novacloud.network,api.dev.novacloud.network,console.dev.novacloud.network,sso.dev.novacloud.network, retry after 2024-09-23T19:53:55Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
``` 
Most likely the auto deployment broke down over the weekend and then every hour autohealing  ate letsencrypt limits (not sure)
So, I try to fix this by temporarily adding in `bearded-wookie-agent-config.yml` additional domain name as available [workaround](https://letsencrypt.org/docs/duplicate-certificate-limit/#workaround). 
It helps to fix this error, but did not fix `bw` as a whole. It looks like some initial state (bootstrap?) is missing. 

`/var/cache/bearded-wookie/deploys` folder is empty on all nodes:
```
ubuntu@nsuite-dev-4c6s:/var/cache/bearded-wookie$ ls -al
total 44
drwxr-xr-x  9 root root 4096 Sep 24 17:35 .
drwxr-xr-x 11 root root 4096 Sep 24 17:34 ..
drwx------  4 root root 4096 Sep 24 17:35 .cached
drwx------  3 root root 4096 Sep 24 17:34 authorizations
drwxr--r--  2 root root 4096 Sep 24 17:35 bootstrap
-rw-------  1 root root   51 Sep 24 17:35 cluster.snapshot
drwxr-xr-x  2 root root 4096 Sep 24 17:34 deploys
-rw-------  1 root root 3243 Sep 24 17:34 p2p.pkey
drwx------  3 root root 4096 Sep 24 17:35 raft.d
drwx------  3 root root 4096 Sep 24 17:35 tls
drwxr-x---  2 root root 4096 Sep 24 17:35 torrents
ubuntu@nsuite-dev-4c6s:/var/cache/bearded-wookie$ ls -al deploys/
total 8
drwxr-xr-x 2 root root 4096 Sep 24 17:34 .
drwxr-xr-x 9 root root 4096 Sep 24 17:35 ..
```
`bw actl quorum ***-dev` or `bw info nodes ***-dev` can't connect and get any information from remote dev laptop 
I will add logs from all three of our instances, maybe this will help to understand the problem better. If you need any additional information, please let me know.
[logs-dev.zip](https://github.com/user-attachments/files/17118525/logs-dev.zip)

**Comment by james-lawrence** [comment]
sorry just saw this @server-nova. between GCP server cycling and lets encrypt issues can crop up. essentially gcp lets itself nuke all servers simultaneously in a autoscaling group. *facepalm*. to unblock you: you can just change the set of dns records for the acme configuration to bypass the rate limits.

alternatively if you want to resolve the issue for good, here is the setup I use for my own systems if you note the dns section for acme thats what you need to do essentially, if you note bootstrap section that filepath points to a fuse mounted gcs-bucket i have on my servers, that would hold the last successful deploy and prevent this outages:

```
root: "$${CACHE_DIRECTORY}"
keepN: 1
minimumNodes: 3
snapshotFrequency: "3h"
servername: "${bearded_wookie_server}"
credentials:
  source: acme
acme:
  # caurl: https://acme-staging-v02.api.letsencrypt.org/directory
  email: "engineering@egdaemon.com"
  secret: "${acme}"
  challenges:
    dns: true
    alpn: false
  dns:
    [
      "${bearded_wookie_certificate_acmebuster_domain}",
      "${bearded_wookie_certificate_console_domain}",
      "${bearded_wookie_certificate_sso_domain}",
      "${bearded_wookie_certificate_ssowildcard_domain}",
    ]
bootstrap:
  # attempts: math.MaxInt32
  readonly: $${ESUITE_PEER_NODE}
  archiveDirectory: "/var/cache/gcsmount-deployments"
notary:
  authority:
    [
      "$${CONFIGURATION_DIRECTORY}/default/bw.auth.keys",
      "/var/cache/bearded-wookie/authorizations/bw.auth.keys",
    ]
clusterTokens:
  - "${token1}"
  - "${token2}"
```
